"""REFUSALS.md's tail, THE SITES -- every `Refused:` in the code, read off the code.

    python tests/refusals.py            rewrites the generated tail of REFUSALS.md
    python tests/refusals.py --check    exit 1 if that tail is stale (CI)

WHY (2026-09-30, WHAT'S LEFT D8; found in the review of 2026-09-28). REFUSALS.md
is written by hand: thirty refusals, each with the sitting that earned it. The
code refuses in more places than that -- 89 `Refused:` sites on the day this
was written, against 66 at the review -- and nothing joined the two: a reader
of the document could not find the line of code, and a reader of the code
could not find the section. This is the mechanical half of the link, the same
way BUILDMAP.md is the map of the code: the sites listed by module, each with
its line and the words the refusal says, regenerated from the code so it
cannot drift, and the count of documented sections beside the count of sites
so the gap is a number on the page rather than a sentence in a handoff. The
hand-written part of the document is never touched: the tail sits between two
markers and only what is between them is rewritten.

Facts read, never generated: the words are the code's own string literal at
each site (placeholders left as `{...}`), and a site whose words cannot be
read whole is listed with as much as the line holds.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "REFUSALS.md"
PKG = ROOT / "manjuel"
OPEN = "<!-- THE SITES: generated by `python tests/refusals.py` -- do not edit below -->"
CLOSE = "<!-- /THE SITES -->"

_SECTION = re.compile(r"^## (\d+[a-z]?)\. ", re.M)
# The words from `Refused:` to the end of the string literal on that line.
_WORDS = re.compile(r"Refused:(.*?)(?:\"|')(?:\s*[)+,]|\s*$|\s*f?\"|\s*#)")


def sites() -> list[tuple[str, int, str]]:
    """(module, line, words) for every line of manjuel/*.py that carries `Refused:`."""
    out = []
    for p in sorted(PKG.glob("*.py")):
        for n, line in enumerate(p.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            if "Refused:" not in line:
                continue
            m = _WORDS.search(line)
            words = (m.group(1) if m else line.split("Refused:", 1)[1]).strip()
            words = words.rstrip("\"'+ ").strip()
            out.append((p.name, n, words or "(the words are on the next line)"))
    return out


def documented(text: str) -> int:
    return len(_SECTION.findall(text))


def tail(text: str) -> str:
    found = sites()
    n_doc = documented(text)
    by_module: dict[str, list[tuple[int, str]]] = {}
    for module, n, words in found:
        by_module.setdefault(module, []).append((n, words))
    out = [OPEN, "", "## THE SITES — every `Refused:` in the code, read off the code", "",
           f"{n_doc} refusals are written up above, by hand, each with the sitting that earned it. "
           f"The code refuses at {len(found)} sites. This tail lists every one -- module, line, and "
           "the words it says -- regenerated from the code by `python tests/refusals.py` so it cannot "
           "drift; `--check` in CI refuses a stale copy. A site is the code's fact; a section above "
           "is the account of why. Where a site's words name a law, a rule or a gate, the section is "
           "the one that names the same.", ""]
    for module in sorted(by_module):
        rows = by_module[module]
        out += [f"### manjuel/{module} — {len(rows)} site{'s' if len(rows) != 1 else ''}", "",
                "| line | says |", "|---|---|"]
        for n, words in rows:
            out.append(f"| {n} | {words.replace('|', '\\\\|')} |")
        out.append("")
    out.append(CLOSE)
    return "\n".join(out) + "\n"


def render(text: str) -> str:
    """The document with its generated tail replaced, or appended if it has none.
    The hand-written part is returned byte for byte."""
    i, j = text.find(OPEN), text.find(CLOSE)
    body = text[:i].rstrip("\n") + "\n\n" if i >= 0 else text.rstrip("\n") + "\n\n"
    return body + tail(text)


def main() -> int:
    raw = DOC.read_bytes()
    crlf = b"\r\n" in raw
    text = raw.decode("utf-8").replace("\r\n", "\n")
    new = render(text)
    if "--check" in sys.argv:
        if new != text:
            print("REFUSALS.md's tail is STALE: regenerate with `python tests/refusals.py`")
            return 1
        print(f"REFUSALS.md's tail matches the code: {len(sites())} sites, {documented(text)} written up.")
        return 0
    DOC.write_bytes((new.replace("\n", "\r\n") if crlf else new).encode("utf-8"))
    print(f"wrote REFUSALS.md's tail: {len(sites())} sites in the code, {documented(text)} written up")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
