"""STATUS.md -- where the ground stands, read off the record. Generated, never hand-edited.

    python tests/status.py            writes STATUS.md at the root
    python tests/status.py --print    prints it instead of writing it
    python tests/status.py --no-gate  leaves the release gate's lines out (fast)

The operator's ask, 2026-09-29: "what are we on as far as the overall build order and path,
versus the docs? What is left for release/deployment? what is missing in packaging?" -- and the
answer cost a hand an hour of reading twenty files. This page is that reading done by
arithmetic: every number on it is read from a file or a repository at the moment it is printed,
the way BUILDMAP.md is read from the code. It judges nothing. The gate judges
(tests/release.py), and this page prints the gate's own lines rather than restating them.

WHAT IT READS, section by section:

    the marks      git: the nearest mark on the main line, how far HEAD stands past it, and
                   main against origin as last fetched; CHANGELOG's Unreleased headings.
                   atlas the same, when atlas/ is a repository here
    the proof      the suites' stamp and the last live standup, by the gate's own staleness
                   rule (release.newest_edit): a green older than the code is STALE
    the gate       release.checks(), every line -- what a mark would be refused on today
    the contract   SPEC.md section 4: MET / OPEN / RULED OUT by subsection, the OPEN lines
                   quoted -- the remaining distance in the contract's own words
    the list       TASKS.md's boxes: open, in hand, landed, declined; the open ones quoted
    the surface    seats, skills, pipelines, flows, the door's tools; lines of code by part
    the record     the ledger's last sitting; DAYBOOK's last entry and its next-session line;
                   HANDOFF's newest block
    packaging      the version pins (core and atlas) and whether they agree; the workflows
                   tracked; the binaries present; what the wheel carries

THE WIRE (RULE 11): tests/release.py's `status` check refuses a mark on the operator's terminal
while STATUS.md is older than the record it reads, so the page cannot go quietly stale between
marks. In CI it is not asked (a checkout carries no mtimes), and says so.

Reads; never writes anything but STATUS.md. No count here is typed by a hand.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_NAME = "STATUS.md"
MARK = "GENERATED by `python tests/status.py`"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import release  # noqa: E402  -- the gate's readers, reused so this page has no second meaning

_DEVNULL = subprocess.DEVNULL


# ---- helpers ------------------------------------------------------------------------

def _git(root: Path, *args: str) -> str:
    """One read of git; "" when there is no repository or git is not here."""
    try:
        p = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True,
                           encoding="utf-8", errors="replace", stdin=_DEVNULL, timeout=30)
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return p.stdout.strip() if p.returncode == 0 else ""


def _when(ts: float | None) -> str:
    return time.strftime("%Y-%m-%d %H:%M", time.localtime(ts)) if ts else "never"


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _lines_of(paths) -> int:
    n = 0
    for p in paths:
        try:
            n += _read(p).count("\n")
        except OSError:
            pass
    return n


def _cut(s: str, width: int = 110) -> str:
    s = " ".join(s.split())
    return s if len(s) <= width else s[:width - 3].rstrip() + "..."


# ---- the marks -----------------------------------------------------------------------

def unreleased_headings(text: str, unreleased_head: str, version_head: re.Pattern) -> list[str]:
    """The `### ` headings under the Unreleased heading, up to the first version heading."""
    out: list[str] = []
    inside = False
    for line in text.splitlines():
        if line.strip() == unreleased_head:
            inside = True
            continue
        if inside and version_head.match(line):
            break
        if inside and line.startswith("### "):
            out.append(line[4:].strip())
    return out


def marks_block(root: Path, name: str, changelog: Path, unreleased_head: str,
                version_head: re.Pattern) -> list[str]:
    out = [f"**{name}**"]
    if not (root / ".git").exists():
        out.append(f"    no repository at {root.name}/ on this machine")
    else:
        head = _git(root, "rev-parse", "--short", "HEAD") or "?"
        branch = _git(root, "branch", "--show-current") or "(detached)"
        near = _git(root, "describe", "--tags", "--abbrev=0", "HEAD")
        ahead = _git(root, "rev-list", "--count", f"{near}..HEAD") if near else ""
        line = f"    on `{branch}` at `{head}`"
        if near:
            line += f"; nearest mark `{near}`, {ahead or '?'} commit(s) past it"
        else:
            line += "; no mark reachable from HEAD"
        out.append(line)
        if _git(root, "rev-parse", "--verify", "-q", "origin/main"):
            lr = _git(root, "rev-list", "--left-right", "--count", "HEAD...origin/main")
            a, b = (lr.split() + ["?", "?"])[:2]
            state = "level" if (a, b) == ("0", "0") else f"ahead {a}, behind {b}"
            out.append(f"    against origin/main as last fetched: {state}")
        else:
            out.append("    no origin/main fetched here")
    heads = unreleased_headings(_read(changelog), unreleased_head, version_head) if changelog.exists() else []
    out.append(f"    {len(heads)} unreleased entr{'y' if len(heads) == 1 else 'ies'} in {changelog.name}"
               + (":" if heads else ""))
    for h in heads:
        out.append(f"      - {_cut(h, 100)}")
    return out


# ---- the proof and the gate ----------------------------------------------------------------

def proof_block(root: Path) -> list[str]:
    edited = release.newest_edit(root)
    out = [f"    newest edit under {', '.join(release.CODE_DIRS)}: {_when(edited)}"]
    stamp = root / "tests" / "last_run.json"
    try:
        book = json.loads(_read(stamp))
        at = max((book.get(s) or {}).get("at") or 0 for s in ("strokes", "smoke"))
        out.append(f"    the suites' stamp: {_when(at)}")
    except Exception:
        out.append("    the suites' stamp: none readable")
    for c in release.suites(root, edited):
        out.append("  " + c.line())
    out.append("  " + release.standup(root, edited).line())
    return out


def gate_block(root: Path, gate: bool) -> list[str]:
    if not gate:
        return ["    not asked on this print (--no-gate); `python tests/release.py --check` asks it"]
    # The gate's `status` check is about THIS page's age, and this page is
    # being printed: asked here it could only say "not yet". It is left to
    # cut time, where the gate reads the page that exists.
    results = [c for c in release.checks(root) if c.name != "status"]
    return (["    " + line for line in release.render(results).splitlines()]
            + ["    (the `status` check is this page's own age, asked of the printed page at cut time)"])


# ---- the contract and the list -------------------------------------------------------------

def contract_block(root: Path) -> list[str]:
    text = _read(root / "SPEC.md")
    if not text:
        return ["    no SPEC.md"]
    statuses = release.spec_statuses(text)
    out: list[str] = []
    section = ""
    open_lines: dict[str, list[str]] = {}
    for line in text.splitlines():
        h = release.SPEC_HEAD.match(line)
        if h:
            section = h.group(1)
            continue
        m = release.SPEC_LINE.match(line) if section else None
        if m and m.group(1) == "OPEN":
            open_lines.setdefault(section, []).append(_cut(line[2:], 120))
    total = {"MET": 0, "OPEN": 0, "RULED OUT": 0}
    for sec, sts in statuses.items():
        counts = {k: sts.count(k) for k in total}
        for k in total:
            total[k] += counts[k]
        out.append(f"    4.{sec.split('.')[1]:<4} MET {counts['MET']:>2}   OPEN {counts['OPEN']:>2}   "
                   f"RULED OUT {counts['RULED OUT']:>2}")
        for ol in open_lines.get(sec, []):
            out.append(f"           OPEN: {ol}")
    out.insert(0, f"    section 4: MET {total['MET']}, OPEN {total['OPEN']}, RULED OUT {total['RULED OUT']}"
                  f" -- DONE is no OPEN line and the standup read on his terminal")
    return out


# TASKS' legend has FOUR states -- open, in hand, landed, declined. The gate's
# own reader (release.task_blocks) knows three, because to the gate `[~]` is
# not a tick and it asks only whether a tick carries a date; this page prints
# the list as the legend defines it, so it reads the fourth too.
_BOX = re.compile(r"^\s+\[([ x~\-])\]\s+(.*)$")


def list_block(root: Path) -> list[str]:
    text = _read(root / "TASKS.md")
    if not text:
        return ["    no TASKS.md"]
    states = {" ": 0, "~": 0, "x": 0, "-": 0}
    opened: list[str] = []
    for line in text.splitlines():
        m = _BOX.match(line)
        if not m or len(re.findall(r"\[[ x~\-]\]", line)) > 1:
            continue                # the legend line names every box; it is not one
        state, title = m.group(1), m.group(2).strip()
        states[state] = states.get(state, 0) + 1
        if state in (" ", "~"):
            opened.append(f"{'[in hand] ' if state == '~' else ''}{_cut(title, 100)}")
    out = [f"    boxes: open {states[' ']}, in hand {states['~']}, landed {states['x']}, "
           f"declined {states['-']} (the operator's list; a hand ticks nothing)"]
    for t in opened:
        out.append(f"      [ ] {t}")
    return out


# ---- the surface -------------------------------------------------------------------------

def surface_block(root: Path) -> list[str]:
    seats = sorted((root / "agents").glob("*.md")) if (root / "agents").is_dir() else []
    skills = sorted((root / "skills").glob("*.md")) if (root / "skills").is_dir() else []
    pipes = len(re.findall(r"^## Pipeline:", _read(root / "pipelines.md"), re.M))
    flows_dir = root / "flows"
    flows = [p for p in flows_dir.glob("*.json") if not re.search(r"\.v\d+\.json$", p.name)] \
        if flows_dir.is_dir() else []
    tools_go = root / "atlas" / "line" / "internal" / "tools" / "tools.go"
    tools = _read(tools_go).count("r.add(Tool{") if tools_go.exists() else None
    out = [f"    seats {len(seats)} · skills {len(skills)} · pipelines {pipes} · flows "
           f"{len(flows) if flows_dir.is_dir() else 'no flows/ here'}"
           + (f" · the door's tools {tools}" if tools is not None else " · no door source here")]
    core = sorted((root / "manjuel").glob("*.py")) if (root / "manjuel").is_dir() else []
    tests = sorted((root / "tests").glob("*.py")) if (root / "tests").is_dir() else []
    out.append(f"    core manjuel/ {len(core)} modules, {_lines_of(core):,} lines; tests/ "
               f"{len(tests)} scripts, {_lines_of(tests):,} lines")
    atlas = root / "atlas"
    if atlas.is_dir():
        go = [p for p in atlas.rglob("*.go") if "node_modules" not in p.parts]
        rs = list(atlas.rglob("*.rs"))
        out.append(f"    atlas/ Go {len(go)} files, {_lines_of(go):,} lines; Rust {len(rs)} files, "
                   f"{_lines_of(rs):,} lines")
    docs = sorted(root.glob("*.md"))
    out.append(f"    root documents {len(docs)}, {_lines_of(docs):,} lines")
    return out


# ---- the record ----------------------------------------------------------------------------

def record_block(root: Path) -> list[str]:
    out: list[str] = []
    ledger = root / "sessions" / "sessions.jsonl"
    last = None
    for line in _read(ledger).splitlines():
        if line.strip():
            try:
                last = json.loads(line)
            except Exception:
                pass
    if last is None:
        out.append("    ledger: no sitting")
    else:
        state = "OPEN" if not last.get("ended") else f"closed {str(last.get('ended'))[:16].replace('T', ' ')}"
        out.append(f"    ledger: sitting {last.get('n')} ({last.get('id')}), {state}")
    day = _read(root / "DAYBOOK.md")
    heads = [l for l in day.splitlines() if l.startswith("## ")]
    out.append(f"    DAYBOOK's last entry: {_cut(heads[-1][3:], 110) if heads else 'none'}")
    nxt = [i for i, l in enumerate(day.splitlines()) if l.startswith("**Next session**")]
    if nxt:
        lines = day.splitlines()
        para: list[str] = []
        for l in lines[nxt[-1]:]:
            if not l.strip():
                break
            para.append(l.strip())
        out.append(f"    its next-session line: {_cut(' '.join(para)[len('**Next session** — '):], 240)}")
    hand = [l for l in _read(root / "HANDOFF.md").splitlines() if l.startswith("## HANDOFF FOR")]
    out.append(f"    HANDOFF's newest block: {_cut(hand[0][3:], 110) if hand else 'none'}")
    return out


# ---- packaging -------------------------------------------------------------------------

def packaging_block(root: Path) -> list[str]:
    out: list[str] = []
    py = re.search(r'^version\s*=\s*"([^"]+)"', _read(root / "pyproject.toml"), re.M)
    init = re.search(r'^__version__\s*=\s*"([^"]+)"', _read(root / "manjuel" / "__init__.py"), re.M)
    a, b = (py.group(1) if py else "?"), (init.group(1) if init else "?")
    out.append(f"    core pins: pyproject {a}, manjuel/__init__ {b} -- "
               + ("agree" if a == b and a != "?" else "DISAGREE"))
    pins = {}
    for rel in ("atlas/VERSION", "atlas/line/VERSION", "atlas/webapp/handlers/VERSION"):
        p = root / rel
        if p.exists():
            pins[rel] = _read(p).strip()
    if pins:
        vals = set(pins.values())
        out.append(f"    atlas pins: {', '.join(f'{k} {v}' for k, v in pins.items())} -- "
                   + ("agree" if len(vals) == 1 else "DISAGREE"))
    wf_dir = root / ".github" / "workflows"
    on_disk = sorted(p.name for p in wf_dir.glob("*.yml")) if wf_dir.is_dir() else []
    tracked = set(_git(root, "ls-files", ".github/workflows").replace("\\", "/").split()) \
        if (root / ".git").exists() else set()
    untracked = [n for n in on_disk if f".github/workflows/{n}" not in tracked]
    out.append(f"    workflows: {', '.join(on_disk) or 'none'}"
               + (f" -- UNTRACKED: {', '.join(untracked)}" if untracked and tracked else ""))
    pk = re.search(r'^packages\s*=\s*\[([^\]]*)\]', _read(root / "pyproject.toml"), re.M)
    out.append(f"    the wheel carries: {pk.group(1).strip() if pk else '?'} -- the declarations "
               f"(agents/, skills/, pipelines.md, law/) are the ground's, not the wheel's")
    for rel in ("atlas/line/atlas-mcp.exe", "atlas/webapp/atlas-webapp.exe"):
        p = root / rel
        out.append(f"    {rel}: " + (f"present, {p.stat().st_size // 1024:,} KB, built {_when(p.stat().st_mtime)}"
                                     if p.exists() else "not here"))
    return out


# ---- the page --------------------------------------------------------------------------

_CORE_VERSION_HEAD = re.compile(r"^## (v\d|\d+\.\d+)")
_ATLAS_VERSION_HEAD = re.compile(r"^## \[(v?\d)")


def render(root: Path = ROOT, gate: bool = True) -> str:
    out = ["# STATUS — where the ground stands", "",
           f"{MARK} from the record at {_when(time.time())}; never hand-edited. Every",
           "number here is read from a file or a repository at that moment, the way BUILDMAP.md is",
           "read from the code; a count you cannot find on disk is a bug in this page, not a fact.",
           "It judges nothing -- the gate judges (tests/release.py) and its lines are printed below.",
           "", "## THE MARKS, AND THE DISTANCE", ""]
    out += marks_block(root, "core", root / "CHANGELOG.md", "## Unreleased", _CORE_VERSION_HEAD)
    if (root / "atlas").is_dir():
        out.append("")
        out += marks_block(root / "atlas", "atlas", root / "atlas" / "CHANGELOG.md",
                           "## [Unreleased]", _ATLAS_VERSION_HEAD)
    out += ["", "## THE PROOF", ""] + proof_block(root)
    out += ["", "## THE GATE -- what a mark would be refused on today", ""] + gate_block(root, gate)
    out += ["", "## THE CONTRACT -- SPEC section 4", ""] + contract_block(root)
    out += ["", "## THE LIST -- TASKS.md", ""] + list_block(root)
    out += ["", "## THE SURFACE", ""] + surface_block(root)
    out += ["", "## THE RECORD", ""] + record_block(root)
    out += ["", "## PACKAGING", ""] + packaging_block(root)
    return "\n".join(out) + "\n"


def write(root: Path = ROOT, gate: bool = True) -> Path:
    text = render(root, gate)
    out = root / OUT_NAME
    out.write_text(text, encoding="utf-8", newline="\r\n")
    return out


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    gate = "--no-gate" not in argv
    if "--print" in argv:
        print(render(ROOT, gate))
        return 0
    out = write(ROOT, gate)
    print(f"wrote {out.name}: {_read(out).count(chr(10))} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
